"""Convert screens from the diamond filesystem and compare them to data in
/tests/test_data/bob_files"""

import difflib
import filecmp
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import OUTPUT_SRC, REFERENCE_DIR

# Stores the converted screens
OUTPUT_DIR = OUTPUT_SRC
# Url to fetch the reference screens from
WEBSERVER_URL = "https://screen-tests-opis.diamond.ac.uk/screen-tests-synoptic/"


def compare_dirs(out_dir, ref_dir):
    """Recursively looks for differences between the freshly converted screens in
    out_dir and the reference screens in ref_dir"""
    all_left = []
    all_right = []
    all_diffs = []
    dcmp = filecmp.dircmp(out_dir, ref_dir, ignore=[".html", "test*"])

    for file in dcmp.diff_files:
        with open(out_dir / file) as test, open(ref_dir / file) as ref:
            lines1 = test.readlines()
            lines2 = ref.readlines()
        diff = difflib.unified_diff(lines1, lines2, fromfile=str(test), tofile=str(ref))
        diff_str = "".join(diff)
        if diff_str != "":
            all_diffs.append(f"Files {test} and {ref} differ:\n{diff_str}")

    if dcmp.left_only:
        all_left.extend([out_dir / file for file in dcmp.left_only])

    if dcmp.right_only:
        all_right.extend([out_dir / file for file in dcmp.right_only])

    for common_dir in dcmp.common_dirs:
        new_dir1 = Path(out_dir) / Path(common_dir)
        new_dir2 = Path(ref_dir) / Path(common_dir)
        left, right, diff_list = compare_dirs(new_dir1, new_dir2)
        all_left.extend(left)
        all_right.extend(right)
        all_diffs.extend(diff_list)

    return all_left, all_right, all_diffs


@pytest.mark.skip(reason="Takes 30 mins, should only be run in specific situations")
def test_front_ends(ref_output_directory):
    """Run the conversion for front_ends.yaml. This requires access to /dls_sw.
    Compare the output to the files saved in the webserver. This can take 30 minutes."""

    # Do conversion from /dls_sw
    cmd = [
        sys.executable,
        "-m",
        "dls_phoebus_converter",
        "-o",
        "test_output/",
        "config/front_ends.yaml",
    ]
    proc = subprocess.Popen(cmd, stderr=subprocess.DEVNULL)
    proc.wait()

    # Get the reference screens from kubernetes

    cmd = [
        "wget",
        "-rq",
        "-nH",
        "--cut-dirs=1",
        "-P",
        str(REFERENCE_DIR),
        WEBSERVER_URL,
    ]
    proc = subprocess.Popen(cmd)
    proc.wait()

    left, right, diffs = compare_dirs(
        OUTPUT_DIR / "fe-services/synoptic", REFERENCE_DIR
    )
    if left or right or diffs:
        print(f"Found the following extra files generated by the conversion: {left}\n")
        print(f"Found the following missing files from the conversion: {right}\n")
        print("The following files have been unexpectedly modified:\n")
        if len(diffs) > 3:
            print("Too many to show")
        else:
            for diff in diffs:
                print(f"{diff}\n")
        raise AssertionError("Found differences in the conversion.")
