meta_data:
  - domain: fe
    domain_synoptic_dst: fe-services/synoptic
    domain_ui_support_dst: fe-ui-support
    acc_ui_support_dst:  acc-ui-support
    convert_dependencies: True


files:
  # Convert FE22B.opi and its dependencies
  - src: tests/test_data/opi_files/FE22B.opi
    dst: synoptic
    template_file: FE22B_template.xml
    macros:
      dom: FE22B
      cell: 22
      mks_type: a
      type: B
      srvalve: 03
      ISBL:
  # Convert all support module screens in the common directory and sub directories
  - src: /dls_sw/prod/R3.14.12.7/support/FE/9-67/FEApp/opi/opi/common
    dst: fe-ui-support
    include_subdirs: true
      
