meta_data:
  - domain: fe
    domain_synoptic_dst: fe-services/synoptic
    domain_ui_support_dst: fe-ui-support/bob
    acc_ui_support_dst:  acc-ui-support/bob
    convert_dependencies: True


files:
  # Convert FE22B.opi and its dependencies
  - src: examples/FE22B.opi
    dst: synoptic
    template_file: FE22B_template.xml
    macros:
      dom: FE22B
      cell: 22
      mks_type: a
      type: B
      srvalve: 03