  # Used by integration/test_conversion_ci.py
meta_data:
  - domain: fe
    domain_synoptic_dst: fe-services/synoptic
    domain_ui_support_dst: fe-ui-support/bob
    acc_ui_support_dst: acc-ui-support/bob

files:
  - src: tests/test_data/opi_files/mks937a
    dst: acc-ui-support
    include_subdirs: true
