meta_data:
  - domain: fe

files:
  # Convert all top level screens and put them in the fe-services repository
  - src: /dls_sw/prod/R3.14.12.7/support/FE/9-67/FEApp/opi/opi
    dst: /scratch/zrv91478/vscode/fe-services/synoptic

  # Convert device screens and put them in the fe-ui-support repository
  - src: /dls_sw/prod/R3.14.12.7/support/FE/9-67/FEApp/opi/opi/common
    dst: /scratch/zrv91478/vscode/fe-ui-support/bob